before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: La9MInltHcyAjHEV1LwZGSt/xdKpu5oTDgfYbDMaVWnS+3Ql7YSb0G0CaxUHYDkYv5OwqExD2LuIfkyAuEju5FdJgzw78nsMlvRhl+B65N58aK8PMGLY+whqqkcs/WV552VTYBcfCPHfJCqYSyvxDwY3XOAI+ZhzcZeLfnMu1UevoJoM2CMK21SDhqXFfhNrjIXEAGI1//UMOl1ecuE8B7HbCowqjbca5+NOR4tS5kZyb/9hXu1yCUoYZsOnL9gTkHkaW1LcTZqAY6FsM+4o1/zWRyHcfwRL0yCNGqQkouZa4rZWxEzXxDl4YL59c85wYYVEn9QMmORJJ10Oe9jO0p7W5/Yyln2+XvQZ+Hdx8imRrIDM8Ck5OUGOtzE87ZjPlMh1vrOFYjhSYXVYkytTEScu8EVoi8Pj2iowQ0oV96JhMCGL0oSNEGRv/pM34PHqDVwiZsbF8BKgfVv9Lg6Je6VkfwUXbkd9XNzbO2hwTI+/giAq5wvcyWL5aZArj81mjKqMf0dHhaarZdUSnHW4uTjYJbpFafU4our0UQZIkYr2/ndhMzykXT5KAl8jDuReOg9R+b5JYbUGfmfzxYFG9mJasdIFz9IGHso5fNBp+16lv164xSgvJjWt+Cd9gAtzZprqknYTUqG1zy7o59zKTaFoOwNt0GUKRw8zxLYbjF0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
